security:
    providers:
        in_memory:
            memory:
                users:
                    paulius:
                        password: $2y$12$s/l56ACmHDia/VSKYXgum.QQHHd8.ya3D70Bi7s3VXn1nt6GWY83O
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: subscribers
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/subscribers, roles: ROLE_ADMIN }
        - { path: ^/categories, roles: ROLE_ADMIN }
        - { path: ^/update, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }